# Copyright 2019 Luca Fedeli
#
# This file is part of picsar
#
# License: BSD-3-Clause-LBNL

# docs:
#   https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html#example-of-complete-lgtmyml-file

extraction:
  cpp:
    prepare:
      packages:
        - cmake
        - libboost-all-dev

    configure:
      command:
        - cmake -S multi_physics/QED                \
            -B build                              \
            -DCMAKE_VERBOSE_MAKEFILE=ON           \
            -DPXRMP_QED_TEST=ON
    index:
      build_command:
        - cmake --build build -j 2

