var namespaces =
[
    [ "boundary", "namespaceboundary.html", null ],
    [ "communications", "namespacecommunications.html", null ],
    [ "constants", "namespaceconstants.html", null ],
    [ "control_file", "namespacecontrol__file.html", null ],
    [ "diagnostics", "namespacediagnostics.html", null ],
    [ "fields", "namespacefields.html", null ],
    [ "grid_tilemodule", "namespacegrid__tilemodule.html", null ],
    [ "itt_fortran", "namespaceitt__fortran.html", null ],
    [ "kyee_em3d", "namespacekyee__em3d.html", null ],
    [ "load_balance", "namespaceload__balance.html", null ],
    [ "matrix_coefficients", "namespacematrix__coefficients.html", null ],
    [ "matrix_data", "namespacematrix__data.html", null ],
    [ "mpi_derived_types", "namespacempi__derived__types.html", null ],
    [ "mpi_routines", "namespacempi__routines.html", null ],
    [ "mpi_type_constants", "namespacempi__type__constants.html", null ],
    [ "output_data", "namespaceoutput__data.html", null ],
    [ "params", "namespaceparams.html", null ],
    [ "particle_properties", "namespaceparticle__properties.html", null ],
    [ "particle_speciesmodule", "namespaceparticle__speciesmodule.html", null ],
    [ "particle_tilemodule", "namespaceparticle__tilemodule.html", null ],
    [ "particles", "namespaceparticles.html", null ],
    [ "precomputed", "namespaceprecomputed.html", null ],
    [ "python_pointers", "namespacepython__pointers.html", null ],
    [ "sde_fortran", "namespacesde__fortran.html", null ],
    [ "shared_data", "namespaceshared__data.html", null ],
    [ "simple_io", "namespacesimple__io.html", null ],
    [ "sorting", "namespacesorting.html", null ],
    [ "tile_params", "namespacetile__params.html", null ],
    [ "tiling", "namespacetiling.html", null ],
    [ "time_stat", "namespacetime__stat.html", null ],
    [ "timing", "namespacetiming.html", null ]
];