name: linux

on: [push, pull_request]

jobs:
  QED:
    name: QED with tests, python bindings, Kokkos examples
    runs-on: ubuntu-20.04
    env: {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"}
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies.sh
    - name: Build & Test
      run: |
        cmake -S multi_physics/QED                \
            -B build                              \
            -DCMAKE_VERBOSE_MAKEFILE=ON           \
            -DPXRMP_QED_TEST=ON                   \
            -DPXRMP_KOKKOS_EXAMPLE=ON             \
            -DKokkos_ENABLE_OPENMP=ON
        cmake --build build -j 2
        cmake --build build --target test
