name: linux

on: [push, pull_request]

jobs:
  QED:
    name: GNU@7.5 C++17 Release [lib]
    runs-on: ubuntu-latest
    env: {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"}
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies.sh
    - name: Build & Install
      run: |
        cmake -S src/multi_physics                \
            -B build                              \
            -DCMAKE_VERBOSE_MAKEFILE=ON
        cmake --build build -j 2
        cmake --build build --target test
