name: macos

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CC: clang
  CXX: clang++
  CXXFLAGS: "-I /usr/local/include -I/usr/local/opt/llvm/include"
  CCFLAGS: "-I /usr/local/include -I/usr/local/opt/llvm/include"
  LDFLAGS: "-L /usr/local/lib -L/usr/local/opt/llvm/lib"

jobs:
  # Build libamrex and all tutorials
  tutorials-macos:
    name: AppleClang@11.0 GFortran@9.3 [tutorials]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh
    - name: Build & Test
      run: |
        export PATH="/usr/local/opt/llvm/bin/:$PATH"
        clang++ -I /usr/local/include -I/usr/local/opt/llvm/include -L /usr/local/lib -L/usr/local/opt/llvm/lib test.cpp
        ./a.out
