name: macos

on: [push, pull_request]

env:
  CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"
  CTEST_OUTPUT_ON_FAILURE: 1
  CC: clang
  CXX: clang++

jobs:
  # Build libamrex and all tutorials
  tutorials-macos:
    name: QED with tests, python bindings, Kokkos examples
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh
    - name: Build & Test
      run: |
        export PATH="/usr/local/opt/llvm/bin/:$PATH"
        cmake -S multi_physics/QED                \
            -B build                              \
            -DCMAKE_VERBOSE_MAKEFILE=ON           \
            -DPXRMP_QED_TEST=ON                   \
            -DPXRMP_KOKKOS_EXAMPLE=ON             \
            -DKokkos_ENABLE_OPENMP=ON
        cmake --build build -j 2
        cmake --build build --target test
