name: macos

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CC: clang
  CXX: clang++
  CXXFLAGS: "-Wall -Wextra -I /usr/local/include -I/usr/local/opt/llvm/include"
  CCFLAGS: "-Wall -Wextra -I /usr/local/include -I/usr/local/opt/llvm/include"
  LDFLAGS: "-L /usr/local/lib"

jobs:
  # Build libamrex and all tutorials
  tutorials-macos:
    name: AppleClang@11.0 GFortran@9.3 [tutorials]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh
    - name: Build & Test
      run: |
        cmake -S multi_physics/QED                \
            -B build                              \
            -DCMAKE_VERBOSE_MAKEFILE=ON           \
            -DPXRMP_QED_TEST=ON
        cmake --build build -j 2
        cmake --build build --target test
